#!/bin/bash
if [ ! -z $USER_1 ]
then
  echo "$USER_1":$(openssl passwd -apr1 $PASS_1) > /etc/squid/passwords
fi
if [ ! -z $USER_2 ]
then
  echo "$USER_1":$(openssl passwd -apr1 $PASS_1) > /etc/squid/passwords
fi
if [ ! -z $USER_3 ]
then
  echo "$USER_1":$(openssl passwd -apr1 $PASS_1) > /etc/squid/passwords
fi
if [ ! -z $USER_4 ]
then
  echo "$USER_1":$(openssl passwd -apr1 $PASS_1) > /etc/squid/passwords
fi
if [ ! -z $USER_5 ]
then
  echo "$USER_1":$(openssl passwd -apr1 $PASS_1) > /etc/squid/passwords
fi
